apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: lab-kubeapps-testing
spec:
  portal:
    title: Developer Readiness Demos
    registration:
      type: anonymous
  workshops:
  - name: lab-kubeapps-testing
    capacity: 1
    expires: 60m
    orphaned: 5m
